require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 3.0.0
  Include:
    - 'app/**/*'
    - 'config/'
    - 'db/**/*'
    - 'lib/tasks/**/*'
    - 'spec/**/*'
    - 'Gemfile'
  Exclude:
    - 'app/javascript/**/*'
    - 'app/assets/**/*'
    - '**/templates/**/*'
    - '**/vendor/**/*'
    - '**/.keep'
    - 'railties/test/fixtures/tmp/**/*'
    - 'actionmailbox/test/dummy/**/*'
    - 'actiontext/test/dummy/**/*'
    - '**/node_modules/**/*'
    - 'db/schema.rb'
    - 'spec/fixtures/**/*'
    - 'bin/*'
    - '**/*.jpeg'

Bundler/OrderedGems:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 35

Metrics/ParameterLists:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: [ 'describe', 'context', 'it' ]
  Max: 50

Metrics/AbcSize:
  Max: 40

Style/Documentation:
  Enabled: false

# Prefer &&/|| over and/or.
Style/AndOr:
  Enabled: true

Style/SymbolArray:
  Enabled: false
  Exclude: [ 'config/**' ]

# Align `when` with `case`.
Layout/CaseIndentation:
  Enabled: true

# Align comments with method definitions.
Layout/CommentIndentation:
  Enabled: true

Layout/ElseAlignment:
  Enabled: true

Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

# Two spaces, no tabs (for indentation).
Layout/IndentationWidth:
  Enabled: true

# Use `foo {}` not `foo{}`.
Layout/SpaceBeforeBlockBraces:
  Enabled: true

# Use `foo { bar }` not `foo {bar}`.
Layout/SpaceInsideBlockBraces:
  Enabled: true
  EnforcedStyleForEmptyBraces: space

# Use `{ a: 1 }` not `{a:1}`.
Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true

Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: true

Layout/LineLength:
  Max: 160