version: '3.3'
services:
  db:
    image: postgres:12.3
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
  redis:
    image: redis:6-alpine
    volumes:
      - redis-data:/var/lib/redis/data
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  postgres:
  redis-data: