default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: travelers_development

test:
  <<: *default
  database: travelers_test

production:
  <<: *default
  database: travelers_production
  password: <%= ENV['TRAVELERS_DATABASE_PASSWORD'] %>
  # url: <%#= ENV['MY_APP_DATABASE_URL'] %>